### ISSUE TITLE
Need comments

### ISSUE THREAD

**Issue by IamLakhan** [Abg4real/my-next-anime#3]
Hey Abg4real, 

I liked the idea of the project and honestly I am inspired to create one like this. However it would be nice to add comments describing what a particular piece of code does to improve the readability, just a suggestion. 
Additionally descriptive commit messages would go a long way in my experience so try to do that too if you can. 

Great project overall, inspiring. Best of luck for the future.

**Comment by Abg4real** [comment]
Hey @IamLakhan 
Thanks for your feedback!
I will make sure to add documentation to code and meaningful commit messages.
Abhishek
